{
 "title": "Ambassador Dashboard",
 "description": "Ambassador dashboard for Prometheus",
 "tags": [ "ambassador" ],
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "listener_port", "label": "Listener port", "query": "http,admin" }
  ]
 },
 "panels": [
  {
   "title": "Ingress CX p/Min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix!=\"admin\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_ssl_active)+sum(envoy_cluster_upstream_cx_active)"
    }
   ]
  },
  {
   "title": "HTTPS Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_ssl_active{envoy_http_conn_manager_prefix!=\"admin\"})"
    }
   ]
  },
  {
   "title": "2xx Per Min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xx Per Min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xx Per Min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))"
    }
   ]
  },
  {
   "title": "Upstream RX Data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name!~\"(xds_cluster|cluster_127_0_0_1_8877)\"})"
    }
   ]
  },
  {
   "title": "Upstream TX Data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name!~\"(xds_cluster|cluster_127_0_0_1_8877)\"})"
    }
   ]
  },
  {
   "title": "Downstream RX Data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix!=\"admin\"})"
    }
   ]
  },
  {
   "title": "Downstream TX Data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix!=\"admin\"})"
    }
   ]
  },
  {
   "title": "Upstream TX KBPs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name!=\"admin\"}[1m]))"
    }
   ]
  },
  {
   "title": "Upstream RX KBPs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name!=\"admin\"}[1m]))"
    }
   ]
  },
  {
   "title": "Downstream TX KBPs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix!=\"admin\"}[1m]))"
    }
   ]
  },
  {
   "title": "Downstream RX KBPs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix!=\"admin\"}[1m]))"
    }
   ]
  },
  {
   "title": "Ambassador Downstream Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"2\", envoy_http_conn_manager_prefix!=\"admin\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"3\", envoy_http_conn_manager_prefix!=\"admin\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\", envoy_http_conn_manager_prefix!=\"admin\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\", envoy_http_conn_manager_prefix!=\"admin\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Ambassador Upstream Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"3\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "RX/TX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bps", "label": "kbps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name!=\"admin\"}[1m]))",
     "legendFormat": "Upstream TX"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name!=\"admin\"}[1m]))",
     "legendFormat": "Upstream RX"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix!=\"admin\"}[1m]))",
     "legendFormat": "Downstream TX"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix!=\"admin\"}[1m]))",
     "legendFormat": "Downstream RX"
    }
   ]
  },
  {
   "title": "API Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_internal_upstream_rq_xx{envoy_response_code_class=\"2\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_internal_upstream_rq_xx{envoy_response_code_class=\"3\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_internal_upstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_internal_upstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Downstream Connections Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {}
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_http1_active[1m]))",
     "legendFormat": "HTTP/1"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_http2_active_active[1m]))",
     "legendFormat": "HTTP/2"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_upgrades_active[1m]))",
     "legendFormat": "Websocket"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream Connections Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_connect_fail) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Transfer Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_rx_bytes_total) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Cluster Update Failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_update_failure) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream Destroy with CX Active",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(envoy_cluster_upstream_cx_destroy_with_active_rq) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "HITS" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_${listener_port}_downstream_rq_xx{envoy_response_code_class=\"2\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_${listener_port}_downstream_rq_xx{envoy_response_code_class=\"3\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_${listener_port}_downstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_${listener_port}_downstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Downstream Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short", "label": "HITS" }
   ],
   "targets": [
    {
     "expr": "avg(increase(envoy_http_downstream_cx_http1_total{envoy_http_conn_manager_prefix=\"ingress_http\"}[1m]))",
     "legendFormat": "Ingress HTTP/1.1"
    },
    {
     "expr": "avg(increase(envoy_http_downstream_cx_http1_total{envoy_http_conn_manager_prefix=\"admin\"}[1m]))",
     "legendFormat": "Admin HTTP/1.1"
    },
    {
     "expr": "avg(increase(envoy_http_downstream_cx_http2_total{envoy_http_conn_manager_prefix=\"ingress_http\"}[1m]))",
     "legendFormat": "Ingress HTTP/2"
    },
    {
     "expr": "avg(increase(envoy_http_downstream_cx_http2_total{envoy_http_conn_manager_prefix=\"admin\"}[1m]))",
     "legendFormat": "Admin HTTP/2"
    }
   ]
  },
  {
   "title": "Downstream Active Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "HITS" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_http1_active{envoy_http_conn_manager_prefix=\"ingress_http\"})",
     "legendFormat": "Ingress HTTP/1.1"
    },
    {
     "expr": "sum(envoy_http_downstream_cx_http1_active{envoy_http_conn_manager_prefix=\"admin\"})",
     "legendFormat": "Admin HTTP/1.1"
    },
    {
     "expr": "sum(envoy_http_downstream_cx_http2_active{envoy_http_conn_manager_prefix=\"ingress_http\"})",
     "legendFormat": "Ingress HTTP/2"
    },
    {
     "expr": "sum(envoy_http_downstream_cx_http2_active{envoy_http_conn_manager_prefix=\"admin\"})",
     "legendFormat": "Admin HTTP/2"
    }
   ]
  }
 ]
}
{
 "title": "Ambassador Edge Stack",
 "description": "Ambassador Edge Stack dashboard for Prometheus",
 "tags": [ "ambassador" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(ambassador_diagnostics_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(ambassador_diagnostics_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Ambassador - Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "ambassador_diagnostics_info{namespace=~\"$namespace\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Last control plane operation time ($pod)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 1 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "ambassador_reconfiguration_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Reconfiguration"
    },
    {
     "expr": "ambassador_fetcher_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Fetcher"
    },
    {
     "expr": "ambassador_aconf_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "AConf"
    },
    {
     "expr": "ambassador_ir_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "IR"
    },
    {
     "expr": "ambassador_econf_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "EConf"
    },
    {
     "expr": "ambassador_diagnostics_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Diagnostics"
    }
   ]
  },
  {
   "title": "Ambassador Edge Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "amb-sidecar memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " ambassador_edge_stack_go_memstats_alloc_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Ambassador - Envoy Data Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Ambassador Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"2\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"3\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "API Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"3\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Downstream Connections Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_cx_length_ms_bucket[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_http1_active[1m]))",
     "legendFormat": "HTTP/1"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_http2_active_active[1m]))",
     "legendFormat": "HTTP/2"
    },
    {
     "expr": "sum(increase(envoy_http_downstream_cx_upgrades_active[1m]))",
     "legendFormat": "Websocket"
    }
   ]
  },
  {
   "title": "Registered Services",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(envoy_cluster_manager_active_clusters)"
    }
   ]
  }
 ]
}